/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as S6RouteImport } from './routes/s6'
import { Route as S5RouteImport } from './routes/s5'
import { Route as S4RouteImport } from './routes/s4'
import { Route as S3RouteImport } from './routes/s3'
import { Route as S2RouteImport } from './routes/s2'
import { Route as S1RouteImport } from './routes/s1'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const S6Route = S6RouteImport.update({
  id: '/s6',
  path: '/s6',
  getParentRoute: () => rootRouteImport,
} as any)
const S5Route = S5RouteImport.update({
  id: '/s5',
  path: '/s5',
  getParentRoute: () => rootRouteImport,
} as any)
const S4Route = S4RouteImport.update({
  id: '/s4',
  path: '/s4',
  getParentRoute: () => rootRouteImport,
} as any)
const S3Route = S3RouteImport.update({
  id: '/s3',
  path: '/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const S2Route = S2RouteImport.update({
  id: '/s2',
  path: '/s2',
  getParentRoute: () => rootRouteImport,
} as any)
const S1Route = S1RouteImport.update({
  id: '/s1',
  path: '/s1',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/instructor': typeof InstructorRoute
  '/missions': typeof MissionsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/s1': typeof S1Route
  '/s2': typeof S2Route
  '/s3': typeof S3Route
  '/s4': typeof S4Route
  '/s5': typeof S5Route
  '/s6': typeof S6Route
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/instructor': typeof InstructorRoute
  '/missions': typeof MissionsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/s1': typeof S1Route
  '/s2': typeof S2Route
  '/s3': typeof S3Route
  '/s4': typeof S4Route
  '/s5': typeof S5Route
  '/s6': typeof S6Route
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/instructor': typeof InstructorRoute
  '/missions': typeof MissionsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/s1': typeof S1Route
  '/s2': typeof S2Route
  '/s3': typeof S3Route
  '/s4': typeof S4Route
  '/s5': typeof S5Route
  '/s6': typeof S6Route
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/instructor'
    | '/missions'
    | '/portfolio'
    | '/privacy'
    | '/s1'
    | '/s2'
    | '/s3'
    | '/s4'
    | '/s5'
    | '/s6'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/instructor'
    | '/missions'
    | '/portfolio'
    | '/privacy'
    | '/s1'
    | '/s2'
    | '/s3'
    | '/s4'
    | '/s5'
    | '/s6'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/instructor'
    | '/missions'
    | '/portfolio'
    | '/privacy'
    | '/s1'
    | '/s2'
    | '/s3'
    | '/s4'
    | '/s5'
    | '/s6'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  InstructorRoute: typeof InstructorRoute
  MissionsRoute: typeof MissionsRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  S1Route: typeof S1Route
  S2Route: typeof S2Route
  S3Route: typeof S3Route
  S4Route: typeof S4Route
  S5Route: typeof S5Route
  S6Route: typeof S6Route
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s6': {
      id: '/s6'
      path: '/s6'
      fullPath: '/s6'
      preLoaderRoute: typeof S6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s5': {
      id: '/s5'
      path: '/s5'
      fullPath: '/s5'
      preLoaderRoute: typeof S5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s4': {
      id: '/s4'
      path: '/s4'
      fullPath: '/s4'
      preLoaderRoute: typeof S4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3': {
      id: '/s3'
      path: '/s3'
      fullPath: '/s3'
      preLoaderRoute: typeof S3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s2': {
      id: '/s2'
      path: '/s2'
      fullPath: '/s2'
      preLoaderRoute: typeof S2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s1': {
      id: '/s1'
      path: '/s1'
      fullPath: '/s1'
      preLoaderRoute: typeof S1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  InstructorRoute: InstructorRoute,
  MissionsRoute: MissionsRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  S1Route: S1Route,
  S2Route: S2Route,
  S3Route: S3Route,
  S4Route: S4Route,
  S5Route: S5Route,
  S6Route: S6Route,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
